// <auto-generated />
using System;
using FitnessProgressionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessProgressionAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517140559_AddExerciseSeedData")]
    partial class AddExerciseSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessProgressionAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Vertical Pull",
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            DifficultyLevel = 3,
                            Family = "Vertical Pull",
                            Name = "Weighted Pull-up"
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            DifficultyLevel = 1,
                            Family = "Vertical Pull",
                            Name = "Pull-down"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            DifficultyLevel = 1,
                            Family = "Horizontal Pull",
                            Name = "Cable Row"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DifficultyLevel = 1,
                            Family = "Horizontal Pull",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Horizontal Pull",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            DifficultyLevel = 1,
                            Family = "Horizontal Push",
                            Name = "Push-up"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Horizontal Push",
                            Name = "Dip"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Horizontal Push",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Vertical Push",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Vertical Push",
                            Name = "Pike Push-up"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            DifficultyLevel = 3,
                            Family = "Vertical Push",
                            Name = "Handstand Push-up"
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            DifficultyLevel = 1,
                            Family = "Squat",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Squat",
                            Name = "Weighted Squat"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            DifficultyLevel = 3,
                            Family = "Squat",
                            Name = "Pistol Squat"
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Hinge",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Core Flexion",
                            Name = "Leg Raise"
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            DifficultyLevel = 3,
                            Family = "Core Static Hold",
                            Name = "Dragon Flag"
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Core Static Hold",
                            Name = "L-Sit"
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            DifficultyLevel = 2,
                            Family = "Core Flexion",
                            Name = "Weighted Cable Crunch"
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            DifficultyLevel = 2,
                            Family = "Core Rotation",
                            Name = "Russian Twist"
                        });
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.ExerciseLog", b =>
                {
                    b.HasOne("FitnessProgressionAPI.Models.Exercise", "Exercise")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessProgressionAPI.Models.Workout", "Workout")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.Workout", b =>
                {
                    b.HasOne("FitnessProgressionAPI.Models.User", null)
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitnessProgressionAPI.Models.Workout", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
